language: node_js

branches:
  only:
  - dev
  - master

notifications:
  slack:
    rooms:
      - binary-group:TI7oyWjkwf9Xx2Rllt2Pr5zY
    on_pull_requests: false

node_js:
  - "8"

install:
  - yarn install

jobs:
  include:
    - stage: test
      script: echo 'No tests are implemented yet...'
    - stage: deploy production
      script:
        - echo 'charts.binary.com' > dist/CNAME
        - yarn gh-pages --repo 'git@github.com:binary-com/SmartCharts.git'
    - stage: deploy beta
      script:
        - yarn gh-pages --repo 'git@github.com:binary-com/SmartCharts.git' --dest './beta'

stages:
  - test
  - name: deploy production
    if: not type in (pull_request) AND branch = master
  - name: deploy beta
    if: not type in (pull_request) AND branch = dev
